### ISSUE TITLE
Output to something else than file, buffer or string.

### ISSUE THREAD

**Issue by a130494** [peterdemartini/html5-to-pdf#11]
First of all thanks, and do not remove the current option of outputting to file.

But I would be happy to get something else that is not written to file, a buffer perhaps.
To return that buffer you could change the callback to a more node style callback with __(err, result)__ for example.
The result value could be an object looking something like this...
```javascript
{ 
    outputType: 'file|buffer|whatever', //the type of output to expect in the output property
    output: <buffer | string> //string with path from outputPath, or buffer etc.
    renderTime: <milliseconds>, //why not spice up the result with some more meta information
    renderSize: <bytes>
    ....
}
```

**Comment by peterdemartini** [comment]
@a130494 I added support for this in `v2.2.0`. Essentially if no outputPath is set, it will return `(error<Error>, buf<Buffer>)` instead of `(error<Error>)`. I decided to just return a buffer since I believe keeping the API simple makes this much more flexible. The render time and size, would be better as a debug option.

**Comment by MeindertRomkes** [comment]
Which v2.2.0.?
